### ISSUE TITLE
Auto-complete fails on Windows systems if 'grep' and 'awk' cannot be found in the PATH environment variable.

### ISSUE THREAD

**Issue by mborgerson** [SublimeText/CTags#111]
**Issue:** Auto-complete fails on Windows systems if `grep` and `awk` cannot be found in the `PATH` environment variable.

**Workaround:** Install Cygwin and add the Cygwin binary directory (C:\Cygwin\bin) to the PATH environment variable. In C:\Cygwin\bin, copy `gawk.exe` to `awk.exe`.

**Comments:** Problem occurs in `ctagsplugin.CTagsAutoComplete.on_query_completions`. The functionality to read the .tags file is already implemented elsewhere in the project, that functionality should be used here.

**Comment by deathaxe** [comment]
awk is no longer used.
