### ISSUE TITLE
How to deal with  "E431: Format error in tags file" ?

### ISSUE THREAD

**Issue by yicai** [SublimeText/CTags#117]
now, I found my ctags has some error . And it is all right  some days ago.

when I use it with hot_key "g + ]" , it always show the error as below:

E431: Format error in tags file "/home/yicailu/code/yr/tags"
Before byte 1188197171
Press ENTER or type command to continue

then I hit ENTER, it show that:

E426: tag not found: abs
Press ENTER or type command to continue

when I use the hot_key "ctr + ]", it can work well sometimes.  I have been rebuilted the tags_file, even re_install the newest ctags. and the error is the same.

my os is ubuntu 10,4,  vim  version 7.2.330;

is anyone see that error, and kindly to tell me how to deal with it ?
Thanks a lot

**Comment by Ole2mail** [comment]
it's been repeated on my side:
- it's exactly 7 lines of some copy-paste source code block
- it's 
:ve
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
- it's Ubuntu 16.04
Linux 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
