### ISSUE TITLE
Error when trying to Rebuild Tags

### ISSUE THREAD

**Issue by josefvn** [SublimeText/CTags#184]
I'm on Mac OS X 10.9, and I'm getting the following error when trying to run **CTags: Rebuild Tags** :

![screen shot 2013-12-18 at 11 51 07 pm](https://f.cloud.github.com/assets/612695/1778046/bdf781a2-682e-11e3-9d68-d59e971bb5fc.png)

error: [Errno 1] b'/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ctags: illegal option -- R\nusage: ctags [-BFadtuwvx] [-f tagsfile] file ...\n'

**Comment by FrancisShi** [comment]
@zigomir, thx~

**Comment by M2shad0w** [comment]
@zigomir thx~  should creat CTags.sublime-settings file in the user folder

**Comment by dramaticlly** [comment]
@zigomir thx, problem solved

**Comment by fenec** [comment]
@zigomir :+1:

**Comment by pod4g** [comment]
@zigomir thx

**Comment by xuwenzhi** [comment]
@zigomir thx!

**Comment by LukeDemons** [comment]
@zigomir it works for me, thx!
