### ISSUE TITLE
Run ctags in background process in ST3

### ISSUE THREAD

**Issue by ghost** [SublimeText/CTags#228]

**Comment by daslicious** [comment]
whats going on with this?

**Comment by ava-dylang** [comment]
Hmm, last I remember, it seemed to be a non issue; But i've stopped using
ctags so I don't recall at all anymore. (The c tags files were the largest
files in our systems and the nice system admins asked me to not need them)

On Wed, May 27, 2015 at 9:55 AM, Damien <notifications@github.com> wrote:

> whats going on with this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublimeText/CTags/issues/228#issuecomment-105992799>.
>



-- 
*Dylan Grafmyre*
*Jr. Developer*

Email: DylanG@conversica.com
Office: +1 (888) 778 1004
Web: www.conversica.com



AVA has changed its name to Conversica. New name. Same innovative product
and people.

The information contained in this electronic mail transmission and its
attachments may be privileged and confidential and
protected from disclosure. If the reader of this message is not the
intended recipient (or an individual responsible for delivery
of the message to such person), you are strictly prohibited from copying,
disseminating or distributing this communication.
If you have received this communication in error, please notify the sender
immediately and destroy all electronic, paper or
other versions.
