### ISSUE TITLE
'ctags' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by joaquintoral** [SublimeText/CTags#243]
I am getting this error after selecting a folder. CTRL + T, CTRL + R shows a list of directories.

**Comment by vk011** [comment]
Hello,  i am getting the same error and can't fix it.

I am using sublime 2 and Windows 7, first I downloaded it thru the package manager, didn't work.

i then downloaded the zip which I extracted and now I have a folder ctags58 in C:\Program Files\Sublime Text 2 and it still doesn't work. I copy/pasted ctags.exe to C:\Program Files\Sublime Text 2 and still it doesn't work.

Is there anything else that can be done?

**Comment by stephenfin** [comment]
@vk011 You could modify the `command` argument in your settings to point to the executable?

**Comment by vk011** [comment]
Thanks for replying, whereexactly do I do that?
And do you mean the executable inside C:\Program Files\Sublime Text 2 or C:\Program Files\Sublime Text 2\ctags58 ?

**Comment by stephenfin** [comment]
Either one will do. Check the [Sublime Text docs](https://www.sublimetext.com/docs/2/settings.html) for info on configuring settings

**Comment by vk011** [comment]
I found the command in Preferences / Package Settings / CTags / Settings - Default , is that what you meant?

Now it looks like so: "command": "C:\\Program Files\\Sublime Text 2\\ctags.exe",

Yet it still shows the same error after restarting sublime.

**Comment by vk011** [comment]
Found it under Ctags / Settings - Default, I copy pasted the exe to C drive now it looks like so and works (in case someone else needs it):

"command": "C:\\ctags.exe",

Thanks!
