### ISSUE TITLE
Packages Conflicts With BufferScroll Restoring Scroll

### ISSUE THREAD

**Issue by titoBouzout** [SublimeText/CTags#280]
Hello, 

Can you please add a setting to the view, when restoring or changing scroll, something like this will work for me:

view.settings('scroll_request_line', 8)
view.settings('scroll_request_row', 18)

So I can check if that setting exists and avoid restoring scrolling. Thanks|

**Comment by stephenfin** [comment]
What would be the purpose of these settings? What would they achieve?

**Comment by titoBouzout** [comment]
bufferscoll changes scroll, if users use CTags, bufferscoll  overwrites the scroll position, the purpose is to avoid the overwritting if CTags was used

**Comment by ltWolfik** [comment]
So, Can you help?

**Comment by stephenfin** [comment]
I can, but it's just another item I have to resolve so it could be a while.
Could you submit even a prototype PR? I can review those much faster than it would take to write it from scratch.
Stephen

**Comment by ltWolfik** [comment]
Sorry, what do you imply "prototype PR"?

**Comment by stephenfin** [comment]
I mean a pull request that demonstrates a fix for this. It can be either of a draft or a complete version - whatever you have time for.

**Comment by ltWolfik** [comment]
I personally can't do this, because i don't know Python. I just have ST3, CTags and BufferScroll plugins. When i use "Navigate to definition" and definition is in new-opened file, BufferScroll overrides Scroll, so i need use "ctrl+k, ctrl+c"(set cursor to center of screen), or use "Navigate to definition" double (so second "Navigate to definition" is for already-open file).

Maybe titoBouzout can do this.
p.s. titoBouzout have added capability to turn off the scroll-synchronization in BufferScroll plugin. So now, i just don't have some functionality. Maybe you would like to fix this conflict, when you'll have time for.
Thanks for answer.

**Comment by titoBouzout** [comment]
Can you please @ltWolfik enable logging by Main menubar -> View -> Show Console, paste this and enter:

    sublime.log_commands(True)

Then replicate the problematic behaviour and paste here the output of the console. Thank you

**Comment by ltWolfik** [comment]
Sorry for my delay.
For example like this:
```python
command: next_view     # file-definition
command: move {"by": "pages", "forward": true} #move out from definition
command: move {"by": "pages", "forward": true}
command: move {"by": "pages", "forward": true}
command: prev_view    # file with using of definition (call for some function)
command: navigate_to_definition  # works correct
command: move {"by": "pages", "forward": true} # move out from definition
command: move {"by": "pages", "forward": true}
command: move {"by": "pages", "forward": true}
command: close   # close file-definition (after i'm in file with using of definition)
command: navigate_to_definition # works incorrect
command: show_at_center  # works incorrect - i'm not in definition (althought in previous time it worked right)
command: prev_view # file with using of definition (call for some function)
command: navigate_to_definition # works correct
```
Thank you.

**Comment by titoBouzout** [comment]
Thansk for your detailed report, can you please update to the latest version of the package, and let me know if still happens. Thanks

**Comment by ltWolfik** [comment]
Sorry for delay. Yes, it still happens(works incorrect). But now show_at_center (ctrl+k, ctrl+c) moves me to definition.
```python
command: navigate_to_definition # i'm in definition
command: move {"by": "pages", "forward": true} # move out from definition
command: move {"by": "pages", "forward": true}
command: prev_view # file with using of the function
command: navigate_to_definition # works correctly
command: move {"by": "pages", "forward": true} # move out from definition
command: move {"by": "pages", "forward": true}
command: close # close file with definition
command: navigate_to_definition # works incorrect
command: show_at_center # now, i'm in definition
```

**Comment by titoBouzout** [comment]
Thanks a lot @ltWolfik for your help, "navigate_to_definition" looks like a text command to me, so I updated it to try to catch it. Can you please update the package to the version I uploaded just now(today), and let me know. Thanks a lot for your time, much appreciated! :)

**Comment by ltWolfik** [comment]
@titoBouzout It works correct! Thanks a lot!
