### ISSUE TITLE
"CTags" can't be found

### ISSUE THREAD

**Issue by spencerkohan** [SublimeText/CTags#287]
I've installed CTags in Sublime Text 3 using the instructions on this blog post:

http://thunderboltlabs.com/blog/2013/11/19/efficiency-with-sublime-text-and-ruby/

So far I've done the following:
1. Installed ctags via `brew install ctags`
2. Installed the CTags sublime text package via Package Install

But when I try to access the settings via Package List > CTags, I get an alert with the following message:

> "CTags" can't be found

Upon farther investigation, there's no folder for CText in the directory: `~/Library/Application Support/Sublime Text 3/Packages`, although there is a package file for CText in `~/Library/Application Support/Sublime Text 3/Installed Packages`.

The message I get when installing the package is `CTags successfully installed`.

When I run `which ctags`, the location I get is `/usr/local/bin/ctags`, and `/usr/local/bin` is right at the beginning of my $PATH.

Any idea what's not working?

**Comment by gronare** [comment]
I have the exact same problem following the same guide, I also corrected according to this post:

http://stackoverflow.com/questions/28067097/how-to-setup-ctags-for-sublime-text-3

Adding the file CTags.sublime-setings manually to the directory, 
~/Library/Application Support/Sublime Text 3/Packages/User/
Without any success...

**Comment by stephenfin** [comment]
This seems to be a common issue on OSX. IIRC there are a number of issues (possibly closed) with resolution for this. I'll have a look through the issues this evening and I suggest ye do the same in case I miss something.

**Comment by stephenfin** [comment]
Seeing as this is a common issue, I think a note in the documentation would make for a good Pull Request.

**Comment by gronare** [comment]
I managed to get it to work by manually installing the plugin. 
I also installed the plugin [Fix Mac Path](https://github.com/int3h/SublimeFixMacPath) if that made any difference.

Following the guide from [Thundeboltlabs.](http://thunderboltlabs.com/blog/2013/11/19/efficiency-with-sublime-text-and-ruby/) Instead of copy and pasting the code into **tags_for_ruby** i used the **nano** editor to rewrite everything, and suddenly it worked! 
From previous experience copying `'´` can mess up a lot.

**Comment by deathaxe** [comment]
Note that GUI applications run sandboxed on MacOS and therefore don't automatically share environment variables from login shell. This kind of issue can be worked around via "Fix Mac Path" on old ST2/3 versions.

More recent ST3 versions started to actively call user's default login shell to query environment, which should solve most "can't find ctags" errors and alike.

There's however nothing the plugin can do against copy & paste errors from blog posts or tutorials.
