### ISSUE TITLE
没有直接跳转到函数定义处

### ISSUE THREAD

**Issue by mqliutie** [SublimeText/CTags#288]
文件目录结构如下
![test](http://images.cnblogs.com/cnblogs_com/mqliutie/687995/o_test.png)
结果如下:
![result](http://images.cnblogs.com/cnblogs_com/mqliutie/687995/o_result.png)
怎么解决呢？

**Comment by stephenfin** [comment]
I'm assuming this is a duplicate of #289, so I'm going to close this one
