### ISSUE TITLE
'show symbols (all)' hangs crashes sublime on big ctag file

### ISSUE THREAD

**Issue by doubleloop** [SublimeText/CTags#290]
I've downloaded linux source code (ftp://ftp.kernel.org/pub/linux/kernel/v3.x/linux-3.13.3.tar.xz), created ctags (193Mb), and tryed to use `show_symbols (all files)` (alt+shift+s). Every time I run it, it immediately hangs sublime and eats my system resources preatty fast (I kill sublime after it takes more then 1gig memory, cpu usage is very high too). It does not even show the popup to enter symbol name. Happens all the time. On the other hadn basic navigation - `show_symbols` (allt+s), `navigate_to_definition` (even to defs in other files) - works fine (and quick).

I am using sublime 3083 on Linux

**Comment by stephenfin** [comment]
Unfortunately this is nigh on impossible to fix. The sheer number of tags available will inevitably crash Sublime Text; as such it's a Sublime Text issue and not a plugin issue.

There are bug reports that report a similar issue.
