### ISSUE TITLE
'ctags' not recognized...

### ISSUE THREAD

**Issue by sajaddp** [SublimeText/CTags#295]
Hello,
I read all docs about installing CTags on sublime!
but i saw this error when I trying for rebuild tags and I cant fix it ):

Please help me step by step
![capture](https://cloud.githubusercontent.com/assets/3147493/9577301/be5ff50c-4ff4-11e5-86ec-48fe945419fc.PNG)

**Comment by rjz1371** [comment]
Yes , me too , i have done all installation process step by step but still i see this error

**Comment by stephenfin** [comment]
Did you try removing the extension?

If this doesn't work, you can put the executable in a folder and [add that folder to your PATH](http://stackoverflow.com/questions/6318156/adding-python-path-on-windows-7). This will fix this for you.
