### ISSUE TITLE
JumpPrev buffer is global

### ISSUE THREAD

**Issue by chuckfossen** [SublimeText/CTags#296]
I have multiple windows open with a project in each one. If I navigate_to_definition in a window, then go back to a previous window where I have called navigate_to_definition and jump_prev, I go to the last file I just navigated from no matter what project/window that I am currently in.

**Comment by deathaxe** [comment]
JumpPrev has been dropped by v0.6.1 in favour of ST3+'s builtin `jump_back` command.
