### ISSUE TITLE
Update to 0.4.0 version : navigate doesn't work for now

### ISSUE THREAD

**Issue by alvolturbo** [SublimeText/CTags#301]
Hi.
"Navigate to Definition" doesn't work after update to 0.4.0 version (ctrl+shift+mouse click, short cuts, and even right click menu).
Restoring from backup the "CTags.sublime-package" file  (version 0.3.9) repairs it back.
What could be wrong with new update?

**Comment by Fabianred** [comment]
Fast Navigation doesn't work at all.
Are there some special sets?

rebuild_ctags			ctrl+t, ctrl+r								<< OK!  >>> 
navigate_to_definition	ctrl+t, ctrl+t	ctrl+>	ctrl+shift+left_click		<< WRONG!  >>> 
jump_prev			ctrl+t, ctrl+b	ctrl+<	ctrl+shift+right_click		<< WRONG!  >>> 
 show_symbols		alt+s										<< OK!  >>>	 
 show_symbols (all files)	alt+shift+s								<< OK!  >>>	 	 
show_symbols (suffix)	ctrl+alt+shift+s								<< WRONG!  >>>

**Comment by Fabianred** [comment]
Hi.
How can I switch off auto update for ctags to version 0.4.0?

**Comment by stephenfin** [comment]
@Fabianred Looking at this today. Pulled the latest version from PackageControl and it's working as expected on Windows 10 (Build 10240). Is this still broken? If so, what platform are you on?

**Comment by Fabianred** [comment]
Hi,
I have just updated the CTAGS from PackageControl and it still doesn't work (size is 41'437 bytes).
I use Windows 7 Ultimate. 
And after each update I have to restore old copy back to folder for proper operations, restart sublime and rebuild tags.

**Comment by Fabianred** [comment]
Hi,
maybe I can send you a sublime archive with all I have installed and all sets?
or I can make a screen video and post it on google drive

**Comment by stephenfin** [comment]
Not a bad idea. Forward the link here and I'll try it out

**Comment by Fabianred** [comment]
here is the backup archive with workable ctags
https://www.dropbox.com/s/fr45oruo0z7sve2/SUBLIME_DROP_BOX.rar?dl=0
try it, please, before and after ctags update

**Comment by Fabianred** [comment]
you can use this example project files to test ctags
https://www.dropbox.com/s/7k3ybj6726ezsb7/TEST_ASM_AVR.rar?dl=0
in my sets for AVR_ASM

**Comment by Fabianred** [comment]
Will you have any updates in nearest future?

**Comment by deathaxe** [comment]
Fixed by 0.5.1
