### ISSUE TITLE
[Bug]:Rebuild tags won't work

### ISSUE THREAD

**Issue by unifreak** [SublimeText/CTags#303]
I never have make this work, changed few computer, changed few installation of sublime and ctag, but it won't work.

I can go into the folder, then run command `ctags -R -f .tags` to manually generate the tags, and it work normally. But whenever I try the `CTag: rebuild tags` in the sublimetext, it will give me such a prompt:

![20151210104114](https://cloud.githubusercontent.com/assets/7945546/11705434/b5f7dcec-9f2a-11e5-9e34-9833acca8e4d.jpg)

And here is the message that I find in console:

```
Building CTags for (some/path): Please be patient
error: 'ctags' ²»ÊÇÄÚ²¿»òÍâ²¿ÃüÁî£¬Ò²²»ÊÇ¿ÉÔËÐÐµÄ³ÌÐò »òÅú´¦ÀíÎÄ¼þ¡£
```

I'm in Win7 64bit, chinese system language

**Comment by mars00772** [comment]
got the same issue,still not figure out how to fix it,

**Comment by 3895177** [comment]
me too

**Comment by 3895177** [comment]
add the ctags.exe to system variables  can solve this problem.
get the ctags.exe:http://ctags.sourceforge.net/

**Comment by UniFreak** [comment]
@3895177 ctags.exe already in C:\windows\system32, I can run it anywhere in the command line. so I don't think that is the problem.

**Comment by mars00772** [comment]
reinstall sublime helps!

**Comment by deathaxe** [comment]
Most likely an encoding issue. universal ctags stores .tags files using utf-8 and CTags 0.5.0+ use same encoding to read and write files.

Former versions used to use `ascii` encoding, which might have been the reason.

Assuming this as fixed for the time being.
