### ISSUE TITLE
Incomplete README

### ISSUE THREAD

**Issue by peetonn** [SublimeText/CTags#307]
In [your README](https://github.com/SublimeText/CTags#settings) you say "In addition to this setting, there's a CTags.sublime-settings file", however there's no information on how to find this file or whether it should be created and placed into any specific directory (OSX). 
Please add that as it's confusing for non-exerienced users.

**Comment by deathaxe** [comment]
Settings are available via Command Palette as of v0.6.0

see `Preferences: CTags Settings`
