### ISSUE TITLE
ST3 Build 3114 incompatible with ctag "Navigate to Definition" functionality

### ISSUE THREAD

**Issue by lizhouli** [SublimeText/CTags#313]
When upgrading to 3114, "Navigate to Definition" functionality in ctag doesn't work again.

It should jump to the function definition normally which works in Build 3103, but now it depends on whether the file the function definition is in is opened,
- when the file is already opened, it will jump to the function definition.
- when the file is not opened, it will open the file and jump to the beginning of the file.

As a workaround, I have to roll back to Build 3103.

**Comment by sardaukar** [comment]
I'm on build 3125, and it kinda works for me, but it always scrolls to the last line of the file if the file is not opened when I navigate to the definition :(

**Comment by mwean** [comment]
I'm having the same problem as @sardaukar. I played around with the timeout in the function that scrolls the definition into view, and 100ms seemed to fix it.

```python
# ctagsplugin.py
def select(view, region):
    sel_set = view.sel()
    sel_set.clear()
    sel_set.add(region)
    sublime.set_timeout(functools.partial(view.show_at_center, region), 100)
```

It seems weird that we have to wait that long before scrolling and that the newer version would cause problems...

**Comment by lizhouli** [comment]
Still weird for me on build 3126 - it jumps to the beginning of the file. 3103 looks the stable version for me...

**Comment by chuckfossen** [comment]
@mwean, that timeout works for me - for now...

**Comment by lizhouli** [comment]
@mwean it works for me too, thanks

**Comment by chuckfossen** [comment]
I still have issues with this.

**Comment by deathaxe** [comment]
Can't reproduce it with ST 3141+.
