### ISSUE TITLE
"find call hierarchy" feature

### ISSUE THREAD

**Issue by mimoo** [SublimeText/CTags#315]
Hey!

In Xcode, you can right click on a function > "find call hierarchy"

it displays a tree showing up all the function calling it, then all the function calling these ones, and on and on. You can super easily see how a function is truly used.

Right now with CTags I can only find the definition/declaration of a function, but not its usages.

![image](http://i.imgur.com/NwwcoL4.png)

**Comment by deathaxe** [comment]
ST doesn't provide an API to display custom tree items. A text based solution in a view or panel doesn't seem viable.
