### ISSUE TITLE
'ctags' is not recognized as an internal or external command...

### ISSUE THREAD

**Issue by VeeK727** [SublimeText/CTags#319]
I'm trying to install ctags on Sublime Text 3 (is it supported?) but this error above. Here's what I've done so  far, as the Readme suggested:
1. Installed ctags from package control
2. Downloaded `ctags.zip` file from the link provided. Unzipped it and copied `ctags.exe` to `C:\Program Files\Sublime Text 3\`
3. In sublime text, right clicked the name of my project and selected "Ctags: Rebuild Tags" which gives me the error. I've read up on the issues that were open previously but their solutions haven't worked, also they were using ST2

Can you tell me if I'm missing something?

**Comment by Peaslek** [comment]
If you copied ctags.exe to C:\Program Files\Sublime Text 3\, make sure C:\Program Files\Sublime Text 3\ is in your path.  You can determine this by typing 'set path' in cmd.

**Comment by VeeK727** [comment]
I was having trouble understanding what it means when the manual said 

> Extract ctags.exe from the downloaded zip to C:\Program Files\Sublime Text 2 or any folder within your PATH so that Sublime Text can run it.

which I understand now. If anyone else is facing the same issue, here's what I did. Go to `Preferences > Package Settings > CTags > Settings - User`

This should open a blank file. Paste the following code and specify the complete location of your `ctags.exe` file in the command name of this object.
```
{
	"command": "C:/Program Files/Sublime Text 3/ctags.exe"
}
```
