### ISSUE TITLE
Ctags uses default Xcode provided ctags

### ISSUE THREAD

**Issue by CatalinMustata** [SublimeText/CTags#326]
I have installed the other version through `brew install ctags` and check `which ctags` points to the correct version. Changed the command in user settings as per instructions... restarted ST3... no luck.

Any suggestions?

**Comment by stephenfin** [comment]
Afraid not. If you look through the [issues](https://github.com/SublimeText/CTags/issues], there are lots of other folks who've had (and resolved) issues on MacOS. Their solutions will probably help you

**Comment by CatalinMustata** [comment]
Managed to fix it. I found the instructions to be somewhat confusing, as I understood that ctags should be under `/usr/bin/` (where the Xcode one is actually) instead of `/usr/local/bin` where the custom one is.

So, for anyone who uses MacOS, after installing ctags, make sure the settings file has `/usr/local/bin/ctags` under the `"command"` setting.

This issue can be closed.

**Comment by stephenfin** [comment]
Ah, thanks for the info. A PR to update the docs would be appreciated, it you fancy it. I'll close this issue in any case though.
