### ISSUE TITLE
ho to rebuild ctags under windows 10

### ISSUE THREAD

**Issue by abramhum** [SublimeText/CTags#327]
H:
I hope to rebuild ctags under windows 10 to make the ctags can support 
javascript better, but I don't know how to do that exactly, 
is any one know to to make that, any suggestion is highly appreciated, thanks 
a lot.

**Comment by deathaxe** [comment]
This plugin just executes ctags and works with content it gets.

Any question with regards to language support should be asked in a ctags related forum or at ctag's repo.
