### ISSUE TITLE
ctags not worked correctly on sublimetext  4152

### ISSUE THREAD

**Issue by eyun221** [SublimeText/CTags#341]
![ctags](https://github.com/SublimeText/CTags/assets/9376835/9314f118-2fdb-44b7-9241-a14689c598ff)
sidebar Menu "CTags: Rebuild Tags" is grey and disabled on 4152, when i degraded to 4143, it's enabled  correctly again.
My os is mac os montery 12.6.7

**Comment by deathaxe** [comment]
`rebuild_tags` command is implemnented as `TextCommand` which have been restricted in usage to fix https://github.com/sublimehq/sublime_text/issues/5781.


related with https://github.com/sublimehq/sublime_text/issues/6062

**Comment by eyun221** [comment]
> 

how to  fix the ctags plugin?
