### ISSUE TITLE
"Jump Back" option is now missing from the right-click context menu

### ISSUE THREAD

**Issue by bpinkney** [SublimeText/CTags#353]
This disappeared yesterday (jan18 2023)

I have tried reloading the package, but the issue persists

Thanks!

**Comment by deathaxe** [comment]
CTags now completely relies on ST's default `jump_back` functionality, available via `alt+-`. The former `jump_prev` no longer exists and most of its frontend entries. Some key bindings, are still in place, though - even though redundant.

**Comment by bpinkney** [comment]
OK, thanks for the info.

Any reason why the right click option can't be plumbed in to the ST `jump_back` option instead of removed outright? It has been useful for accessibility.

**Comment by sublimator** [comment]
Just lurking
Kinda cool seeing this still worked on
I wrote first version in 2008 or sth like that - ST1 days

**Comment by sublimator** [comment]
IntelliJ tragic these days
Sublime just for TODO.txt

**Comment by deathaxe** [comment]
1. It seems out of scope for a plugin to provide menu entries for unrelated foreign (in this case built-in) commands. 
_Actually also thought about dropping related key bindings for the same reason._
2. Depending on amount of installed plugins, context menu tends to grow quickly.

Context menu can be customized by adding a `Packages/User/Context.sublime-menu`.

```json
[
	{
		"command": "jump_forward"
	},
	{
		"command": "jump_back"
	}
]
```

**Comment by bpinkney** [comment]
OKNice, good tip, thanks!
