### ISSUE TITLE
Can't build tags on OS X Mountain LIon

### ISSUE THREAD

**Issue by oleksandr-diudiun** [SublimeText/CTags#90]
(ReOpened Issue from https://github.com/SublimeText/CTags/issues/18 becouse problem still need to answer)

OS  X 10.8
ST 2
ctags 5.8 installed from mac ports 

 I'm getting the following error:

`EnvironmentError: (u'ctags -R -f .tags', 1, 'ctags: illegal option -- R\nusage: ctags [-BFadtuwvx] [-f tagsfile] file ...\n')`

But running ctags -R -f .tags works fine from the terminal (with sudo and without sudo). 
And if I run ST2 from termainal with sudo (like `:user$ sudo open /Applic.../S..T..2/...`), all works fine
Any thoughts?

**Comment by nejadb** [comment]
@brianlow 
Worked for me! Even with "which ctags" pointing to the correct location I needed this in my settings to get it to work. Thank you.

**Comment by muhammad-meraj** [comment]
@brianlow , Thanks, it works.
